# Generated by Django 4.2.4 on 2024-02-01 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practical',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Practical',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
