# Generated by Django 4.2.4 on 2024-02-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitapp', '0004_theorytest'),
    ]

    operations = [
        migrations.AddField(
            model_name='theorytest',
            name='option2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='theorytest',
            name='option3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='theorytest',
            name='option4',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='theorytest',
            name='answer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='theorytest',
            name='option1',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
