# Generated by Django 4.2.4 on 2024-03-30 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitapp', '0005_theorytest_option2_theorytest_option3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scorebar', models.IntegerField(default=0)),
                ('hired', models.BooleanField(default=False)),
                ('elligible', models.BooleanField(default=False)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eng', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
