# Generated by Django 5.0.4 on 2024-04-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitapp', '0006_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(default='Engineer', max_length=500),
        ),
    ]
